added pdf download and csv conversion
liwoo/mse-scraper-2 pull request #2
Opened 2022-03-20 12:20 UTC by sevenreup

2022-03-20 17:15 UTC, liwoo requested changes

2022-03-20 17:15 UTC, liwoo commented on downloader/msePdfDownloader.go
> +		if err == nil {
which `err` is this?

2022-03-20 17:15 UTC, liwoo commented on downloader/msePdfDownloader.go
> +			func() {
extract to private function called `attemptCsvConversion`

2022-04-16 13:57 UTC, sevenreup commented on downloader/msePdfDownloader.go
> +		if err == nil {
referred to the wrong one

2022-04-16 14:03 UTC, sevenreup commented on downloader/msePdfDownloader.go
> +		if err == nil {
referred to the wrong one

2022-04-20 14:16 UTC, liwoo approved these changes

2022-04-20 14:16 UTC, merged